# EXAMPLE ONLY - AI Provider Plugin Demonstration
from plugins.contracts.ai_contract import BaseAIProviderPlugin
from typing import Dict, Any, Optional

class ExampleAIPlugin(BaseAIProviderPlugin):
    async def transcribe(self, audio_file_path: str) -> Dict[str, Any]:
        return {
            "text": "Transcribed by Example AI Provider.",
            "language": "en",
            "duration": 30.0,
            "segments": [{"sequence": 1, "start_time": 0.0, "end_time": 30.0, "text": "Transcribed audio"}]
        }

    async def analyze_content(self, title: str, transcript_text: str, segments=None) -> Dict[str, Any]:
        return {
            "title": title,
            "summary": "Sample summary generated by Example AI Provider.",
            "key_topics": ["Technology", "AI"],
            "target_audience": "Developers",
            "hooks": ["Discover how custom AI plugins work."]
        }

    async def generate_platform(self, platform: str, brief: Dict[str, Any], segments=None, tone="professional", custom_instructions=None) -> Dict[str, Any]:
        return {
            "platform": platform,
            "text_content": f"Example AI generated copy for {platform}.",
            "hashtags": ["#Reflow", "#AI"]
        }

    async def plan_carousel(self, title: str, brief=None, transcript_text=None, target_slide_count=5, template="MINIMAL", tone="informative", custom_instructions=None) -> Dict[str, Any]:
        return {
            "title": title,
            "template": template,
            "slides": [{"position": i, "headline": f"Slide {i}", "body": "Content body", "layout": "TITLE_BODY"} for i in range(1, target_slide_count + 1)]
        }

    async def discover_clips(self, title: str, transcript_text: str, segments: list, brief=None, min_duration=15.0, max_duration=90.0, target_count=5) -> Dict[str, Any]:
        return {
            "candidates": [{"title": "Example Clip Highlight", "start_time": 0.0, "end_time": 20.0, "hook": "Awesome highlight", "virality_score": 90.0}]
        }
